create sequence SEQUENCE_BOOKING start with 1 increment by 1;
create sequence SEQUENCE_ROOM start with 1 increment by 1;
create sequence SEQUENCE_USER start with 1 increment by 1;
create table BOOKINGS (ID number(10,0) not null, DATE_FROM date, DATE_TO date, ROOM_ID number(10,0) not null, USER_ID number(10,0) not null, primary key (ID));
create table ROOMS (ID number(10,0) not null, ROOM_NR number(10,0), TYPE varchar2(255), primary key (ID));
create table USERS (ID number(10,0) not null, NAME varchar2(255), PESEL varchar2(255), SURNAME varchar2(255), primary key (ID));
alter table BOOKINGS add constraint FKcj4plqkgnewmvojjof79orcq3 foreign key (ROOM_ID) references ROOMS;
alter table BOOKINGS add constraint FKipoo9hhxuydu9rjxh1iln4g33 foreign key (USER_ID) references USERS;
commit;
insert into USERS (ID, NAME, PESEL, SURNAME) values (SEQUENCE_USER.nextval, 'Grazyna', '64021351413', 'Rudnik');
insert into USERS (ID, NAME, PESEL, SURNAME) values (SEQUENCE_USER.nextval, 'Rozalia', '84021351413', 'Gadek');
insert into USERS (ID, NAME, PESEL, SURNAME) values (SEQUENCE_USER.nextval, 'Paula', '94021351413', 'Dudus');
insert into USERS (ID, NAME, PESEL, SURNAME) values (SEQUENCE_USER.nextval, 'Marek', '64021351413', 'Baniak');
insert into USERS (ID, NAME, PESEL, SURNAME) values (SEQUENCE_USER.nextval, 'Judasz', '69021351413', 'Conte');
insert into USERS (ID, NAME, PESEL, SURNAME) values (SEQUENCE_USER.nextval, 'Janusz', '74021351413', 'Kowalski');
insert into USERS (ID, NAME, PESEL, SURNAME) values (SEQUENCE_USER.nextval, 'Wladek', '34021351413', 'Zodiak');
insert into ROOMS (ID, ROOM_NR, TYPE) values (SEQUENCE_ROOM.nextval, 101, 'SINGLE');
insert into ROOMS (ID, ROOM_NR, TYPE) values (SEQUENCE_ROOM.nextval, 102, 'DOUBLE');
insert into ROOMS (ID, ROOM_NR, TYPE) values (SEQUENCE_ROOM.nextval, 103, 'SINGLE');
insert into ROOMS (ID, ROOM_NR, TYPE) values (SEQUENCE_ROOM.nextval, 201, 'DOUBLE');
insert into ROOMS (ID, ROOM_NR, TYPE) values (SEQUENCE_ROOM.nextval, 202, 'DOUBLE');
insert into ROOMS (ID, ROOM_NR, TYPE) values (SEQUENCE_ROOM.nextval, 203, 'DOUBLE');
insert into ROOMS (ID, ROOM_NR, TYPE) values (SEQUENCE_ROOM.nextval, 301, 'SINGLE');
insert into ROOMS (ID, ROOM_NR, TYPE) values (SEQUENCE_ROOM.nextval, 302, 'SINGLE');